from typing import Protocol

from wrs_debugger.models.device import ReceiverInfo, SerialPortInfo, TransmitterInfo
from wrs_debugger.models.gfsk import GfskParameters
from wrs_debugger.models.lora import LoRaParameters


class BindingHandle:
    """Opaque internal binding transaction handle; never serialized or logged."""

    def __init__(self, value: str) -> None:
        self.value = value


class WrsGateway(Protocol):
    def list_serial_ports(self) -> list[SerialPortInfo]: ...
    def connect_transmitter(self, device: str) -> None: ...
    def disconnect_transmitter(self) -> None: ...
    def read_transmitter_info(self) -> TransmitterInfo: ...
    def read_transmitter_pin(self) -> str: ...
    def write_transmitter_pin(self, pin: str) -> None: ...
    def read_transmitter_lora_parameters(self) -> LoRaParameters: ...
    def write_transmitter_lora_parameters(self, parameters: LoRaParameters) -> None: ...
    def restore_transmitter_lora_defaults(self) -> None: ...
    def read_transmitter_gfsk_parameters(self) -> GfskParameters: ...
    def write_transmitter_gfsk_parameters(self, parameters: GfskParameters) -> None: ...
    def restore_transmitter_gfsk_defaults(self) -> None: ...
    def connect_receiver(self, domain_id: int) -> None: ...
    def disconnect_receiver(self) -> None: ...
    def read_receiver_info(self) -> ReceiverInfo: ...
    def read_receiver_lora_parameters(self) -> LoRaParameters: ...
    def write_receiver_lora_parameters(self, parameters: LoRaParameters) -> None: ...
    def restore_receiver_lora_defaults(self) -> None: ...
    def read_receiver_gfsk_parameters(self) -> GfskParameters: ...
    def write_receiver_gfsk_parameters(self, parameters: GfskParameters) -> None: ...
    def restore_receiver_gfsk_defaults(self) -> None: ...
    def prepare_transmitter_binding(self) -> BindingHandle: ...
    def prepare_receiver_binding(self, handle: BindingHandle) -> None: ...
    def verify_binding(self, handle: BindingHandle) -> None: ...
    def rollback_binding(self, handle: BindingHandle) -> None: ...
